### ISSUE TITLE
Can't access cookie in preHandler

### ISSUE THREAD

**Issue by Mat-thieu** [fastify/fastify-cookie#5]
The cookie object doesn't seem to exist in the `preHandler` hook inside my routes, see my code below;

```javascript
// routes/auth.js
// inside routes function
  fastify.register(require('fastify-cookie'), (err) => {
    if (err) throw err
  });

  fastify.addHook('preHandler', (request, reply, done) => {
    if(request.cookie) { // always fails
      done();
      return;
    }
    reply.code(403).send({
      error: 'Unauthorized',
      message: 'No cookie',
      statusCode: 404
    });
  });

  fastify.post('/register', async (request, reply) => {
    // Cookie exists here
    const user = await User.create(request.body);
    return { data: user };
  });
```

I'm certain the cookie actually exists.
I know the middleware utilizes the `preHandler` to set the cookie object, is that the reason it can't be accessed inside any other `preHandler`?

**Comment by mcollina** [comment]
It might be. However it might also be a bug. I fear we might be adding the prehandlers in the weong order.

The best way to achieve this is to set beforeHandler when you define your route.

**Comment by nwoltman** [comment]
In your example, you should be using `request.cookies` (with an `s` at the end).

Other than that, what's happening here is that calls to `fastify.register` are asynchronous, so the `fastify-cookie` plugin gets registered after you add your `preHandler` hook, which means that your `preHandler` hook will run before the cookie `preHandler` hook.

This may get fixed in a future release of `fastify`, but for now you can make the hooks get registered in the right order by using fastify's `after` method:

```js
fastify
  .register(require('fastify-cookie'))
  .after((err, done) => {
    fastify.addHook('preHandler', ...)
    done(err)
  })

**Comment by Mat-thieu** [comment]
@nwoltman Sorry made some last minute adjustments to the example, in my actual code it's `cookies`.
Your solutions works, I suggest you update the readme with that example because I can imagine it's not uncommon to want to use the cookie in a preHandler.

@mcollina That also works, @nwoltman 's solution saves me a little repetition though :)

Thanks for the rapid response guys! Loving the framework so far.
